// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TheBuryProject.Data;

#nullable disable

namespace TheBuryProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507000000_AddCreditoRestriccionCuotasSnap")]
    partial class AddCreditoRestriccionCuotasSnap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model snapshot omitted — regenerate with: dotnet ef migrations add
#pragma warning restore 612, 618
        }
    }
}
