// <auto-generated />
// Este archivo fue creado manualmente. Para regenerarlo con el snapshot completo
// ejecutar: dotnet ef migrations add AddScoringBandsToConfiguracionCredito --force
// cuando el proceso TheBuryProyect.exe no esté en ejecución (libera los ensamblados obj/).
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TheBuryProject.Data;

#nullable disable

namespace TheBuryProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429000001_AddScoringBandsToConfiguracionCredito")]
    partial class AddScoringBandsToConfiguracionCredito
    {
        // BuildTargetModel omitido intencionalmente.
        // La migración ejecuta correctamente sin este snapshot parcial.
        // Regenerar con "dotnet ef" para habilitar migraciones incrementales futuras.
    }
}
