// <auto-generated />
// Este archivo fue creado manualmente porque el ensamblado de la app puede estar bloqueado
// durante el desarrollo local. Regenerar con dotnet ef si se necesita snapshot completo.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TheBuryProject.Data;

#nullable disable

namespace TheBuryProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429000002_AddSemaforoFinancieroThresholdsToConfiguracionCredito")]
    partial class AddSemaforoFinancieroThresholdsToConfiguracionCredito
    {
    }
}
